using FluentAssertions;
using PPDS.DocsGen.Common;
using Xunit;

namespace PPDS.DocsGen.Common.Tests;

public class BannerHelperTests
{
    [Fact]
    public void AutogeneratedBanner_IncludesToolName()
    {
        var banner = BannerHelper.AutogeneratedBanner("cli-reflect");

        banner.Should().Contain("cli-reflect");
        banner.Should().Contain("Auto-generated");
        banner.Should().Contain("overwritten");
    }
}
