import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const REPO_ROOT = resolve(__dirname, '..', '..');
const SCRIPT = resolve(REPO_ROOT, 'scripts', 'docs-gen', 'ext-reflect', 'generate.js');
const FIXTURE_ROOT = resolve(__dirname, 'fixtures', 'ext-reflect');
const FIXTURE_PKG = resolve(FIXTURE_ROOT, 'package.json');
const EXPECTED_DIR = resolve(FIXTURE_ROOT, 'expected');

function runGenerator(packageJson: string, output: string) {
  const result = spawnSync(
    process.execPath,
    [SCRIPT, '--package-json', packageJson, '--output', output],
    { encoding: 'utf8' },
  );
  return {
    exitCode: result.status,
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
  };
}

function makeTmpDir(): string {
  return mkdtempSync(join(tmpdir(), 'ext-reflect-'));
}

describe('ExtReflectTests', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('EmitsExpectedCommandsTable', () => {
    // AC-18: generator output for commands.md matches the committed expected file byte-for-byte.
    const { exitCode, stderr } = runGenerator(FIXTURE_PKG, tmpDir);
    expect(stderr).toBe('');
    expect(exitCode).toBe(0);

    const actual = readFileSync(join(tmpDir, 'commands.md'), 'utf8');
    const expected = readFileSync(join(EXPECTED_DIR, 'commands.md'), 'utf8');
    expect(actual).toBe(expected);
  });

  it('EmitsExpectedConfigurationMarkdown', () => {
    const { exitCode } = runGenerator(FIXTURE_PKG, tmpDir);
    expect(exitCode).toBe(0);

    const actual = readFileSync(join(tmpDir, 'configuration.md'), 'utf8');
    const expected = readFileSync(join(EXPECTED_DIR, 'configuration.md'), 'utf8');
    expect(actual).toBe(expected);
  });

  it('EmitsExpectedViewsMarkdown', () => {
    const { exitCode } = runGenerator(FIXTURE_PKG, tmpDir);
    expect(exitCode).toBe(0);

    const actual = readFileSync(join(tmpDir, 'views.md'), 'utf8');
    const expected = readFileSync(join(EXPECTED_DIR, 'views.md'), 'utf8');
    expect(actual).toBe(expected);
  });

  it('DeterministicOutputAcrossRuns', () => {
    // AC-19 (Ext): running the generator twice on the same input produces byte-identical output.
    const firstOut = join(tmpDir, 'first');
    const secondOut = join(tmpDir, 'second');

    const a = runGenerator(FIXTURE_PKG, firstOut);
    const b = runGenerator(FIXTURE_PKG, secondOut);
    expect(a.exitCode).toBe(0);
    expect(b.exitCode).toBe(0);

    for (const name of ['commands.md', 'configuration.md', 'views.md']) {
      const first = readFileSync(join(firstOut, name), 'utf8');
      const second = readFileSync(join(secondOut, name), 'utf8');
      expect(first).toBe(second);
    }
  });

  it('HandlesMissingContributesSection', () => {
    // Package.json with no 'contributes' → three files with (none) placeholders, exit 0.
    const tmpPkg = join(tmpDir, 'package.json');
    writeFileSync(
      tmpPkg,
      JSON.stringify({ name: 'no-contributes', version: '0.0.1', private: true }, null, 2),
      'utf8',
    );
    const out = join(tmpDir, 'out');

    const { exitCode, stderr } = runGenerator(tmpPkg, out);
    expect(stderr).toBe('');
    expect(exitCode).toBe(0);

    for (const name of ['commands.md', 'configuration.md', 'views.md']) {
      const full = join(out, name);
      expect(existsSync(full)).toBe(true);
      const body = readFileSync(full, 'utf8');
      expect(body).toContain('Auto-generated by scripts/docs-gen/ext-reflect');
      expect(body).toContain('(none)');
    }
  });
});
