// Strict MDX parse validator used by MdxParseTests.StrictMdxAcceptsGeneratedReference.
// Reads file paths from argv, compiles each via @mdx-js/mdx, and exits 0 if all
// parse cleanly. First failure writes `{file}:{error}` to stderr and exits 1.
//
// Kept intentionally tiny — no formatting, no caching, no concurrency. If it
// grows past ~40 lines someone has added a feature that belongs elsewhere.

import { readFile } from 'node:fs/promises';
import { extname } from 'node:path';
import { compile } from '@mdx-js/mdx';

const files = process.argv.slice(2);
if (files.length === 0) {
  console.error('parse.mjs: no files supplied');
  process.exit(2);
}

for (const file of files) {
  try {
    const source = await readFile(file, 'utf8');
    // Match Docusaurus' loader behaviour: `.md` files parse in markdown
    // format (HTML comments + raw HTML allowed); `.mdx` files parse in
    // strict MDX format. The generators produce `.md` today — the fixture
    // directories bear this out — so forcing MDX format here would reject
    // the legitimate autogenerated banner comment. Route by extension.
    const ext = extname(file).toLowerCase();
    const format = ext === '.mdx' ? 'mdx' : 'md';
    await compile(source, { format });
  } catch (err) {
    const msg = err && err.message ? err.message : String(err);
    process.stderr.write(`${file}:${msg}\n`);
    process.exit(1);
  }
}

process.exit(0);
