namespace PPDS.DocsGen.Common;

/// <summary>
/// Emits the standard top-of-file banner included in every generated doc.
/// Signals to humans (and to our auto-restore tooling) that the file is
/// machine-produced.
/// </summary>
public static class BannerHelper
{
    /// <summary>
    /// Returns the autogenerated-file banner comment for the given tool
    /// (e.g. <c>cli-reflect</c>, <c>libs-reflect</c>, <c>mcp-reflect</c>,
    /// <c>ext-reflect</c>).
    /// </summary>
    public static string AutogeneratedBanner(string toolName) =>
        $"<!-- Auto-generated by scripts/docs-gen/{toolName} — edits will be overwritten on next release. -->";
}
