#!/usr/bin/env python3
"""
Generate specs/README.md from spec frontmatter.

Scrapes H1, Status, Surfaces, Code, and first Overview sentence from each
spec file and produces a sorted markdown table. The README is never
hand-edited — this script is the single source of truth.

Usage: python scripts/generate-spec-readme.py
"""
import os
import re
import sys


def extract_frontmatter(filepath):
    """Extract metadata from a spec file's frontmatter and overview."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")

    # H1 title
    title = None
    for line in lines:
        if line.startswith("# "):
            title = line[2:].strip()
            break

    if not title:
        return None

    # Status
    status = "—"
    for line in lines:
        m = re.match(r"\*\*Status:\*\*\s*(.*)", line)
        if m:
            status = m.group(1).strip()
            break

    # Surfaces
    surfaces = "—"
    for line in lines:
        m = re.match(r"\*\*Surfaces:\*\*\s*(.*)", line)
        if m:
            surfaces = m.group(1).strip()
            break

    # Code paths
    code = "—"
    for line in lines:
        m = re.match(r"\*\*Code:\*\*\s*(.*)", line)
        if m:
            raw = m.group(1).strip()
            # Extract path prefixes from markdown links like [path/](../path/)
            paths = re.findall(r"\[([^\]]+)\]\([^)]+\)", raw)
            if paths:
                code = ", ".join(f"`{p}`" for p in paths)
            elif raw.lower() not in ("none", ""):
                code = raw
            break

    # First sentence of Overview section
    purpose = "—"
    in_overview = False
    for line in lines:
        if line.strip() == "## Overview":
            in_overview = True
            continue
        if in_overview and line.strip() and not line.startswith("#"):
            # Take first sentence
            sentence = re.split(r"(?<=[.!?])\s", line.strip())[0]
            purpose = sentence
            break

    return {
        "title": title,
        "status": status,
        "surfaces": surfaces,
        "code": code,
        "purpose": purpose,
    }


def main():
    # Determine specs directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    specs_dir = os.path.join(repo_root, "specs")

    if not os.path.isdir(specs_dir):
        print(f"Error: specs directory not found at {specs_dir}", file=sys.stderr)
        sys.exit(1)

    # Exclusions
    exclude = {"CONSTITUTION.md", "SPEC-TEMPLATE.md", "README.md"}

    # Collect spec metadata
    specs = []
    for filename in sorted(os.listdir(specs_dir)):
        if not filename.endswith(".md") or filename in exclude:
            continue
        filepath = os.path.join(specs_dir, filename)
        meta = extract_frontmatter(filepath)
        if meta:
            meta["filename"] = filename
            specs.append(meta)

    # Sort alphabetically by filename
    specs.sort(key=lambda s: s["filename"])

    # Generate README
    lines = [
        "# Specifications",
        "",
        "> **Constitution:** All specs must comply with [CONSTITUTION.md](./CONSTITUTION.md).",
        "> See Spec Laws (SL1–SL5) for naming, lifecycle, and granularity rules.",
        "",
        "<!-- AUTO-GENERATED — do not edit. Regenerated by /spec or scripts/generate-spec-readme.py -->",
        "",
        "| Spec | Status | Surfaces | Code | Purpose |",
        "|------|--------|----------|------|---------|",
    ]

    for spec in specs:
        name = spec["filename"]
        link = f"[{name}](./{name})"
        lines.append(
            f"| {link} | {spec['status']} | {spec['surfaces']} | {spec['code']} | {spec['purpose']} |"
        )

    lines.append("")

    readme_path = os.path.join(specs_dir, "README.md")
    with open(readme_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Generated {readme_path} with {len(specs)} specs.", file=sys.stderr)


if __name__ == "__main__":
    main()
