using System.Text;
using PPDS.DocsGen.Common;

namespace PPDS.DocsGen.Cli;

/// <summary>
/// Deterministic markdown rendering for commands and group indexes. Uses LF
/// line endings explicitly so output is byte-identical across host OSes
/// (AC-19).
/// </summary>
internal static class MarkdownRenderer
{
    private const string Lf = "\n";

    public static string RenderCommand(CliReferenceGenerator.DiscoveredCommand cmd)
    {
        var sb = new StringBuilder();
        sb.Append(BannerHelper.AutogeneratedBanner(CliReferenceGenerator.ToolName)).Append(Lf);
        sb.Append(Lf);
        sb.Append("# ").Append(cmd.CommandName).Append(Lf);
        sb.Append(Lf);

        if (!string.IsNullOrWhiteSpace(cmd.Description))
        {
            sb.Append(MdxEscape.Prose(cmd.Description)).Append(Lf);
            sb.Append(Lf);
        }

        sb.Append("## Usage").Append(Lf);
        sb.Append(Lf);
        sb.Append("```").Append(Lf);
        sb.Append("ppds ").Append(cmd.GroupName).Append(' ').Append(cmd.CommandName).Append(" [options]").Append(Lf);
        sb.Append("```").Append(Lf);
        sb.Append(Lf);

        if (cmd.Arguments.Count > 0)
        {
            sb.Append("## Arguments").Append(Lf);
            sb.Append(Lf);
            sb.Append("| Name | Required | Description |").Append(Lf);
            sb.Append("| --- | --- | --- |").Append(Lf);
            foreach (var a in cmd.Arguments)
            {
                sb.Append("| ")
                    .Append(MdxEscape.InlineCode(a.Name))
                    .Append(" | ")
                    .Append(a.Required ? "yes" : "no")
                    .Append(" | ")
                    .Append(MdxEscape.Prose(a.Description ?? string.Empty))
                    .Append(" |").Append(Lf);
            }
            sb.Append(Lf);
        }

        if (cmd.Options.Count > 0)
        {
            sb.Append("## Options").Append(Lf);
            sb.Append(Lf);
            sb.Append("| Long | Short | Type | Default | Description |").Append(Lf);
            sb.Append("| --- | --- | --- | --- | --- |").Append(Lf);
            foreach (var o in cmd.Options)
            {
                sb.Append("| ")
                    .Append(MdxEscape.InlineCode(o.LongName ?? string.Empty))
                    .Append(" | ")
                    .Append(string.IsNullOrEmpty(o.ShortName) ? string.Empty : MdxEscape.InlineCode(o.ShortName))
                    .Append(" | ")
                    .Append(MdxEscape.InlineCode(o.TypeDisplay))
                    .Append(" | ")
                    .Append(string.IsNullOrEmpty(o.DefaultValue) ? string.Empty : MdxEscape.InlineCode(o.DefaultValue))
                    .Append(" | ")
                    .Append(MdxEscape.Prose(o.Description ?? string.Empty))
                    .Append(" |").Append(Lf);
            }
            sb.Append(Lf);
        }

        return sb.ToString();
    }

    public static string RenderGroupIndex(string groupName, IReadOnlyList<CliReferenceGenerator.DiscoveredCommand> commands)
    {
        var sb = new StringBuilder();
        sb.Append(BannerHelper.AutogeneratedBanner(CliReferenceGenerator.ToolName)).Append(Lf);
        sb.Append(Lf);
        sb.Append("# ").Append(groupName).Append(" commands").Append(Lf);
        sb.Append(Lf);
        sb.Append("| Command | Description |").Append(Lf);
        sb.Append("| --- | --- |").Append(Lf);
        foreach (var c in commands)
        {
            sb.Append("| ")
                .Append(MdxEscape.InlineCode(c.CommandName))
                .Append(" | ")
                .Append(MdxEscape.Prose(c.Description ?? string.Empty))
                .Append(" |").Append(Lf);
        }
        sb.Append(Lf);

        return sb.ToString();
    }
}
