#!/usr/bin/env node
// Emit markdown reference for the PPDS VS Code extension from its package.json.
// Spec: specs/docs-generation.md — Surface-Specific §Extension, AC-18, AC-19.
//
// Usage:
//   node scripts/docs-gen/ext-reflect/generate.js \
//     --package-json <path> --output <dir>
//
// Exit codes:
//   0 — all three markdown files written
//   1 — invalid JSON, missing required args, or write error

'use strict';

const fs = require('fs');
const path = require('path');

const BANNER = '<!-- Auto-generated by scripts/docs-gen/ext-reflect \u2014 edits will be overwritten on next release. -->';

function escape(s) {
  if (s === null || s === undefined) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function code(s) {
  if (s === null || s === undefined || s === '') return '';
  return '`' + String(s) + '`';
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i];
    if (flag === '--package-json' || flag === '--output') {
      const next = argv[i + 1];
      if (!next) {
        process.stderr.write(`ext-reflect: ${flag} requires a value\n`);
        process.exit(1);
      }
      args[flag === '--package-json' ? 'packageJson' : 'output'] = next;
      i++;
    } else {
      process.stderr.write(`ext-reflect: unknown argument '${flag}'\n`);
      process.exit(1);
    }
  }
  if (!args.packageJson) {
    process.stderr.write('ext-reflect: --package-json is required\n');
    process.exit(1);
  }
  if (!args.output) {
    process.stderr.write('ext-reflect: --output is required\n');
    process.exit(1);
  }
  return args;
}

function renderCommands(contributes) {
  const commands = Array.isArray(contributes.commands) ? contributes.commands.slice() : [];
  const keybindings = Array.isArray(contributes.keybindings) ? contributes.keybindings : [];
  const keyByCommand = {};
  for (const kb of keybindings) {
    if (kb && typeof kb.command === 'string' && !keyByCommand[kb.command]) {
      keyByCommand[kb.command] = kb;
    }
  }
  commands.sort((a, b) => String(a.command || '').localeCompare(String(b.command || '')));

  const lines = [BANNER, '', '# Commands', ''];
  if (commands.length === 0) {
    lines.push('(none)', '');
    return lines.join('\n');
  }
  lines.push('| Command ID | Title | Category | Default Keybinding | When Clause |');
  lines.push('|---|---|---|---|---|');
  for (const cmd of commands) {
    const id = code(cmd.command || '');
    const title = escape(cmd.title || '');
    const category = escape(cmd.category || '');
    const kb = keyByCommand[cmd.command];
    const key = kb && kb.key ? code(kb.key) : '';
    const when = kb && kb.when ? code(kb.when) : '';
    lines.push(`| ${id} | ${title} | ${category} | ${key} | ${when} |`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderConfiguration(contributes) {
  const config = contributes.configuration || {};
  const properties = config.properties && typeof config.properties === 'object' ? config.properties : {};
  const keys = Object.keys(properties).sort();

  const lines = [BANNER, '', '# Configuration', ''];
  if (keys.length === 0) {
    lines.push('(none)', '');
    return lines.join('\n');
  }
  lines.push('| Setting | Type | Default | Description |');
  lines.push('|---|---|---|---|');
  for (const key of keys) {
    const prop = properties[key] || {};
    const type = code(prop.type || '');
    let def = '';
    if (Object.prototype.hasOwnProperty.call(prop, 'default')) {
      def = code(JSON.stringify(prop.default));
    }
    const desc = escape(prop.description || '');
    lines.push(`| ${code(key)} | ${type} | ${def} | ${desc} |`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderViews(contributes) {
  const containers = contributes.viewsContainers && typeof contributes.viewsContainers === 'object'
    ? contributes.viewsContainers
    : {};
  const views = contributes.views && typeof contributes.views === 'object' ? contributes.views : {};

  const containerEntries = [];
  const knownContainerIds = new Set();
  const locations = Object.keys(containers).sort();
  for (const location of locations) {
    const arr = Array.isArray(containers[location]) ? containers[location].slice() : [];
    arr.sort((a, b) => String(a.id || '').localeCompare(String(b.id || '')));
    for (const c of arr) {
      if (c && typeof c.id === 'string') knownContainerIds.add(c.id);
      containerEntries.push({ location, container: c });
    }
  }

  const lines = [BANNER, '', '# Views', ''];
  if (containerEntries.length === 0 && Object.keys(views).length === 0) {
    lines.push('(none)', '');
    return lines.join('\n');
  }

  for (const { location, container } of containerEntries) {
    const cid = container.id || '';
    const title = escape(container.title || '');
    lines.push(`## ${code(cid)} (${escape(location)})`);
    lines.push('');
    if (title) {
      lines.push(`Title: ${title}`);
      lines.push('');
    }
    const containerViews = Array.isArray(views[cid]) ? views[cid].slice() : [];
    containerViews.sort((a, b) => String(a.id || '').localeCompare(String(b.id || '')));
    if (containerViews.length === 0) {
      lines.push('(no views)');
    } else {
      for (const v of containerViews) {
        const vid = code(v.id || '');
        const vname = escape(v.name || '');
        lines.push(`- ${vid} \u2014 ${vname}`);
      }
    }
    lines.push('');
  }

  const orphanKeys = Object.keys(views).filter(k => !knownContainerIds.has(k)).sort();
  for (const k of orphanKeys) {
    lines.push(`## ${code(k)}`);
    lines.push('');
    const arr = Array.isArray(views[k]) ? views[k].slice() : [];
    arr.sort((a, b) => String(a.id || '').localeCompare(String(b.id || '')));
    for (const v of arr) {
      lines.push(`- ${code(v.id || '')} \u2014 ${escape(v.name || '')}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function main(argv) {
  const { packageJson, output } = parseArgs(argv);

  let raw;
  try {
    raw = fs.readFileSync(path.resolve(packageJson), 'utf8');
  } catch (err) {
    process.stderr.write(`ext-reflect: cannot read '${packageJson}': ${err.message}\n`);
    process.exit(1);
  }

  let pkg;
  try {
    pkg = JSON.parse(raw);
  } catch (err) {
    process.stderr.write(`ext-reflect: invalid JSON in '${packageJson}': ${err.message}\n`);
    process.exit(1);
  }

  const contributes = (pkg && pkg.contributes && typeof pkg.contributes === 'object') ? pkg.contributes : {};

  const outputs = {
    'commands.md': renderCommands(contributes),
    'configuration.md': renderConfiguration(contributes),
    'views.md': renderViews(contributes),
  };

  try {
    fs.mkdirSync(path.resolve(output), { recursive: true });
  } catch (err) {
    process.stderr.write(`ext-reflect: cannot create output directory '${output}': ${err.message}\n`);
    process.exit(1);
  }

  const written = [];
  for (const name of Object.keys(outputs).sort()) {
    const full = path.resolve(output, name);
    try {
      fs.writeFileSync(full, outputs[name], 'utf8');
      written.push(full);
    } catch (err) {
      process.stderr.write(`ext-reflect: cannot write '${full}': ${err.message}\n`);
      process.exit(1);
    }
  }

  for (const p of written.slice().sort()) {
    process.stdout.write(p + '\n');
  }
  process.exit(0);
}

main(process.argv.slice(2));
